version: '3'
services:
  api:
    image: node:12.18.4
    working_dir: /code
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code

  db:
    image: mongo:latest
    volumes:
      - "./api/db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=raad
volumes:
  dbdata: