services:
  # client:
  #   container_name: debug_dev_client
  #   build: ./client
  #   image: debug_client
  #   ports: 
  #     - 8080:8080
  #   working_dir: /code
  #   volumes:
  #     - type: bind
  #       source: ./client
  #       target: /code
  #   command: [ "http-server" ]
  api:
    container_name: debug_dev_api
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=traker
      - DB_CONNECTION=mongodb://raad:trackerpass@db:27017
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  db:
    container_name: debug_dev_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
    environment: 
      - MONGO_INITDB_DATABASE=tracker
      - MONGO_INITDB_ROOT_PASSWORD=trackerpass
volumes:
  dbdata:
networks: 
  default:
    name: debug_api